# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: customer_service/customer_registration.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='customer_service/customer_registration.proto',
  package='customer',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n,customer_service/customer_registration.proto\x12\x08\x63ustomer\"=\n\x08\x43ustomer\x12\x14\n\x0c\x63ustomer_ref\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"C\n\x1b\x43ustomerRegistrationRequest\x12$\n\x08\x63ustomer\x18\x01 \x01(\x0b\x32\x12.customer.Customer\"@\n\x1c\x43ustomerRegistrationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"5\n\x1dGetCustomerByReferenceRequest\x12\x14\n\x0c\x63ustomer_ref\x18\x01 \x01(\t\"U\n\x1eGetCustomerByReferenceResponse\x12$\n\x08\x63ustomer\x18\x01 \x01(\x0b\x32\x12.customer.Customer\x12\r\n\x05\x66ound\x18\x02 \x01(\x08\"*\n\x19GetCustomerByEmailRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"Q\n\x1aGetCustomerByEmailResponse\x12$\n\x08\x63ustomer\x18\x01 \x01(\x0b\x32\x12.customer.Customer\x12\r\n\x05\x66ound\x18\x02 \x01(\x08\x32\xd2\x02\n\x14\x43ustomerRegistration\x12\x66\n\x15register_new_customer\x12%.customer.CustomerRegistrationRequest\x1a&.customer.CustomerRegistrationResponse\x12n\n\x19get_customer_by_reference\x12\'.customer.GetCustomerByReferenceRequest\x1a(.customer.GetCustomerByReferenceResponse\x12\x62\n\x15get_customer_by_email\x12#.customer.GetCustomerByEmailRequest\x1a$.customer.GetCustomerByEmailResponseb\x06proto3'
)




_CUSTOMER = _descriptor.Descriptor(
  name='Customer',
  full_name='customer.Customer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='customer_ref', full_name='customer.Customer.customer_ref', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='customer.Customer.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='email', full_name='customer.Customer.email', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=119,
)


_CUSTOMERREGISTRATIONREQUEST = _descriptor.Descriptor(
  name='CustomerRegistrationRequest',
  full_name='customer.CustomerRegistrationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='customer', full_name='customer.CustomerRegistrationRequest.customer', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=188,
)


_CUSTOMERREGISTRATIONRESPONSE = _descriptor.Descriptor(
  name='CustomerRegistrationResponse',
  full_name='customer.CustomerRegistrationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='customer.CustomerRegistrationResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='customer.CustomerRegistrationResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=190,
  serialized_end=254,
)


_GETCUSTOMERBYREFERENCEREQUEST = _descriptor.Descriptor(
  name='GetCustomerByReferenceRequest',
  full_name='customer.GetCustomerByReferenceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='customer_ref', full_name='customer.GetCustomerByReferenceRequest.customer_ref', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=256,
  serialized_end=309,
)


_GETCUSTOMERBYREFERENCERESPONSE = _descriptor.Descriptor(
  name='GetCustomerByReferenceResponse',
  full_name='customer.GetCustomerByReferenceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='customer', full_name='customer.GetCustomerByReferenceResponse.customer', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='found', full_name='customer.GetCustomerByReferenceResponse.found', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=311,
  serialized_end=396,
)


_GETCUSTOMERBYEMAILREQUEST = _descriptor.Descriptor(
  name='GetCustomerByEmailRequest',
  full_name='customer.GetCustomerByEmailRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='email', full_name='customer.GetCustomerByEmailRequest.email', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=398,
  serialized_end=440,
)


_GETCUSTOMERBYEMAILRESPONSE = _descriptor.Descriptor(
  name='GetCustomerByEmailResponse',
  full_name='customer.GetCustomerByEmailResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='customer', full_name='customer.GetCustomerByEmailResponse.customer', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='found', full_name='customer.GetCustomerByEmailResponse.found', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=442,
  serialized_end=523,
)

_CUSTOMERREGISTRATIONREQUEST.fields_by_name['customer'].message_type = _CUSTOMER
_GETCUSTOMERBYREFERENCERESPONSE.fields_by_name['customer'].message_type = _CUSTOMER
_GETCUSTOMERBYEMAILRESPONSE.fields_by_name['customer'].message_type = _CUSTOMER
DESCRIPTOR.message_types_by_name['Customer'] = _CUSTOMER
DESCRIPTOR.message_types_by_name['CustomerRegistrationRequest'] = _CUSTOMERREGISTRATIONREQUEST
DESCRIPTOR.message_types_by_name['CustomerRegistrationResponse'] = _CUSTOMERREGISTRATIONRESPONSE
DESCRIPTOR.message_types_by_name['GetCustomerByReferenceRequest'] = _GETCUSTOMERBYREFERENCEREQUEST
DESCRIPTOR.message_types_by_name['GetCustomerByReferenceResponse'] = _GETCUSTOMERBYREFERENCERESPONSE
DESCRIPTOR.message_types_by_name['GetCustomerByEmailRequest'] = _GETCUSTOMERBYEMAILREQUEST
DESCRIPTOR.message_types_by_name['GetCustomerByEmailResponse'] = _GETCUSTOMERBYEMAILRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Customer = _reflection.GeneratedProtocolMessageType('Customer', (_message.Message,), {
  'DESCRIPTOR' : _CUSTOMER,
  '__module__' : 'customer_service.customer_registration_pb2'
  # @@protoc_insertion_point(class_scope:customer.Customer)
  })
_sym_db.RegisterMessage(Customer)

CustomerRegistrationRequest = _reflection.GeneratedProtocolMessageType('CustomerRegistrationRequest', (_message.Message,), {
  'DESCRIPTOR' : _CUSTOMERREGISTRATIONREQUEST,
  '__module__' : 'customer_service.customer_registration_pb2'
  # @@protoc_insertion_point(class_scope:customer.CustomerRegistrationRequest)
  })
_sym_db.RegisterMessage(CustomerRegistrationRequest)

CustomerRegistrationResponse = _reflection.GeneratedProtocolMessageType('CustomerRegistrationResponse', (_message.Message,), {
  'DESCRIPTOR' : _CUSTOMERREGISTRATIONRESPONSE,
  '__module__' : 'customer_service.customer_registration_pb2'
  # @@protoc_insertion_point(class_scope:customer.CustomerRegistrationResponse)
  })
_sym_db.RegisterMessage(CustomerRegistrationResponse)

GetCustomerByReferenceRequest = _reflection.GeneratedProtocolMessageType('GetCustomerByReferenceRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETCUSTOMERBYREFERENCEREQUEST,
  '__module__' : 'customer_service.customer_registration_pb2'
  # @@protoc_insertion_point(class_scope:customer.GetCustomerByReferenceRequest)
  })
_sym_db.RegisterMessage(GetCustomerByReferenceRequest)

GetCustomerByReferenceResponse = _reflection.GeneratedProtocolMessageType('GetCustomerByReferenceResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETCUSTOMERBYREFERENCERESPONSE,
  '__module__' : 'customer_service.customer_registration_pb2'
  # @@protoc_insertion_point(class_scope:customer.GetCustomerByReferenceResponse)
  })
_sym_db.RegisterMessage(GetCustomerByReferenceResponse)

GetCustomerByEmailRequest = _reflection.GeneratedProtocolMessageType('GetCustomerByEmailRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETCUSTOMERBYEMAILREQUEST,
  '__module__' : 'customer_service.customer_registration_pb2'
  # @@protoc_insertion_point(class_scope:customer.GetCustomerByEmailRequest)
  })
_sym_db.RegisterMessage(GetCustomerByEmailRequest)

GetCustomerByEmailResponse = _reflection.GeneratedProtocolMessageType('GetCustomerByEmailResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETCUSTOMERBYEMAILRESPONSE,
  '__module__' : 'customer_service.customer_registration_pb2'
  # @@protoc_insertion_point(class_scope:customer.GetCustomerByEmailResponse)
  })
_sym_db.RegisterMessage(GetCustomerByEmailResponse)



_CUSTOMERREGISTRATION = _descriptor.ServiceDescriptor(
  name='CustomerRegistration',
  full_name='customer.CustomerRegistration',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=526,
  serialized_end=864,
  methods=[
  _descriptor.MethodDescriptor(
    name='register_new_customer',
    full_name='customer.CustomerRegistration.register_new_customer',
    index=0,
    containing_service=None,
    input_type=_CUSTOMERREGISTRATIONREQUEST,
    output_type=_CUSTOMERREGISTRATIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get_customer_by_reference',
    full_name='customer.CustomerRegistration.get_customer_by_reference',
    index=1,
    containing_service=None,
    input_type=_GETCUSTOMERBYREFERENCEREQUEST,
    output_type=_GETCUSTOMERBYREFERENCERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get_customer_by_email',
    full_name='customer.CustomerRegistration.get_customer_by_email',
    index=2,
    containing_service=None,
    input_type=_GETCUSTOMERBYEMAILREQUEST,
    output_type=_GETCUSTOMERBYEMAILRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CUSTOMERREGISTRATION)

DESCRIPTOR.services_by_name['CustomerRegistration'] = _CUSTOMERREGISTRATION

# @@protoc_insertion_point(module_scope)
